### PR TITLE
Release Outline Manager v1.13.0

### PR DESCRIPTION
**Pull request by jyyi1**
**Changelog**

- [invite flow improvement](https://github.com/Jigsaw-Code/outline-server/pull/1198)

### CODE REVIEW

**Comment by jyyi1** [comment]
> Are all the build numbers correct?

I think so, they are exactly the same as S3, and I've tested the auto update on all platforms.

**Comment by jyyi1** [comment]
@daniellacosse @fortuna  please feel free to add anything to the change log, and approve the pr. Thanks.

**Comment by bardia13s** [comment]
outline v1.13 is new or v1.19 ? I dont know which should to choose please help

**Comment by jyyi1** [comment]
@bardia13s where did you find v1.19?

1.13 should be the latest one.

**Comment by fortuna** [comment]
v1.19 is the client.

**Pull request merged**
